using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Mini.BloodCult;

[GenerateTypedNameReferences]
public sealed partial class BloodCultRoundStartMenu : FancyWindow
{
    public BloodCultRoundStartMenu()
    {
        RobustXamlLoader.Load(this);
        ConfirmButton.OnPressed += _ => Close();
    }
}
