// SPDX-FileCopyrightText: 2022 Kevin Zheng <kevinz5000@gmail.com>
// SPDX-FileCopyrightText: 2022 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
// SPDX-FileCopyrightText: 2022 Veritius <veritiusgaming@gmail.com>
// SPDX-FileCopyrightText: 2022 ike709 <ike709@github.com>
// SPDX-FileCopyrightText: 2022 ike709 <ike709@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 metalgearsloth <metalgearsloth@gmail.com>
// SPDX-FileCopyrightText: 2022 mirrorcult <lunarautomaton6@gmail.com>
// SPDX-FileCopyrightText: 2024 Leon Friedrich <60421075+ElectroJr@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Nemanja <98561806+EmoGarbage404@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 ShadowCommander <10494922+ShadowCommander@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.Guidebook;
using Content.Client.Guidebook.Controls;
using Content.Client.Guidebook.RichText;
using Content.Client.UserInterface.Systems.Info;
using Content.Shared.Guidebook;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.ContentPack;
using Robust.Shared.Prototypes;

namespace Content.Client.Info;

[GenerateTypedNameReferences]
public sealed partial class RulesControl : BoxContainer, ILinkClickHandler
{
    [Dependency] private readonly DocumentParsingManager _parsingMan = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IResourceManager _resource = default!;

    private static readonly ISawmill Sawmill = Logger.GetSawmill("rules");

    private ProtoId<GuideEntryPrototype>? _currentEntry;
    private readonly Stack<ProtoId<GuideEntryPrototype>> _priorEntries = new();

    public RulesControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        RulesPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#1C1C28"),
        };

        HomeButton.OnPressed += _ => SetGuide();

        BackButton.OnPressed += _ =>
        {
            if (_priorEntries.Count == 0)
                return;

            SetGuide(_priorEntries.Pop(), addToPrior: false);
        };
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        UserInterfaceManager.DeferAction(Refresh);
    }

    public void Refresh()
    {
        _priorEntries.Clear();
        _currentEntry = null;
        UserInterfaceManager.DeferAction(() => SetGuide());
    }

    public void HandleClick(string link)
    {
        SetGuide(link);
    }

    private void SetGuide(ProtoId<GuideEntryPrototype>? entry = null, bool addToPrior = true)
    {
        if (!VisibleInTree)
        {
            UserInterfaceManager.DeferAction(() => SetGuide(entry, addToPrior));
            return;
        }

        var coreEntry = UserInterfaceManager.GetUIController<InfoUIController>().GetCoreRuleEntry();
        var entryId = entry ?? new ProtoId<GuideEntryPrototype>(coreEntry.ID);

        Scroll.SetScrollValue(default);
        RulesContainer.Children.Clear();

        if (!_prototype.TryIndex(entryId, out var guideEntry))
        {
            Sawmill.Error($"Unknown rules guide entry: {entryId}");
            RulesContainer.AddChild(new GuidebookError($"Unknown rules guide entry: {entryId}", string.Empty));
            return;
        }

        using var file = _resource.ContentFileReadText(guideEntry.Text);
        if (!_parsingMan.TryAddMarkup(RulesContainer, file.ReadToEnd()))
        {
            Sawmill.Error($"Failed to parse rules guide entry: {entryId}");
            return;
        }

        if (RulesContainer.ChildCount == 0)
        {
            Sawmill.Error($"Rules guide entry {entryId} produced no controls");
            RulesContainer.AddChild(new GuidebookError($"Rules guide entry {entryId} is empty", string.Empty));
            return;
        }

        if (addToPrior && _currentEntry != null)
            _priorEntries.Push(_currentEntry.Value);
        _currentEntry = entryId;

        HomeButton.Visible = entryId != coreEntry.ID;
        BackButton.Visible = _priorEntries.Count != 0 && _priorEntries.Peek() != entryId;
    }
}
