// SPDX-FileCopyrightText: 2024 Leon Friedrich <60421075+ElectroJr@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 ShadowCommander <10494922+ShadowCommander@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Collections.Generic;
using System.Numerics;
using Content.Client.Lobby.UI;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Guidebook;
using Content.Shared.Localization;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Lobby.UI.Roles;

/// <summary>
/// A generic locking selector.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class RequirementsSelector : BoxContainer
{
    private readonly RadioOptions<int> _options;
    private readonly StripeBack _lockStripe;
    private readonly RoleLockIcon _lockIcon;
    private readonly List<(Button Button, Color Color)> _coloredButtons = [];
    private Dictionary<int, Color>? _buttonColors;
    private List<ProtoId<GuideEntryPrototype>>? _guides;
    private float _optionButtonMinWidth = 90;
    private float _optionButtonMinHeight;

    public event Action<int>? OnSelected;
    public event Action<List<ProtoId<GuideEntryPrototype>>>? OnOpenGuidebook;

    public int Selected => _options.SelectedId;

    public RequirementsSelector()
    {
        RobustXamlLoader.Load(this);
        _options = new RadioOptions<int>(RadioOptionsLayout.Horizontal)
        {
            FirstButtonStyle = StyleBase.ButtonOpenRight,
            ButtonStyle = StyleBase.ButtonOpenBoth,
            LastButtonStyle = StyleBase.ButtonOpenLeft,
            HorizontalExpand = true,
        };
        _options.GenerateItem = GenerateButton;

        _options.OnItemSelected += args =>
        {
            _options.Select(args.Id);
            UpdateButtonColors();
            OnSelected?.Invoke(args.Id);
        };

        var requirementsLabel = new RoleLockIcon
        {
            Visible = true,
        };

        _lockStripe = new StripeBack()
        {
            Visible = false,
            HorizontalExpand = true,
            HasMargins = false,
            MouseFilter = MouseFilterMode.Stop,
            Children =
            {
                new CenterContainer
                {
                    Children = { requirementsLabel },
                },
            }
        };
        _lockIcon = requirementsLabel;

        Help.OnPressed += _ =>
        {
            if (_guides != null)
                OnOpenGuidebook?.Invoke(_guides);
        };
    }

    public void Setup(
        (string, int)[] items,
        string title,
        int titleSize,
        string? description,
        TextureRect? icon = null,
        List<ProtoId<GuideEntryPrototype>>? guides = null,
        Dictionary<int, Color>? buttonColors = null,
        float optionButtonMinWidth = 90,
        float optionButtonMinHeight = 0,
        float? optionsContainerWidth = null)
    {
        _buttonColors = buttonColors;
        _coloredButtons.Clear();
        _optionButtonMinWidth = optionButtonMinWidth;
        _optionButtonMinHeight = optionButtonMinHeight;

        foreach (var (text, value) in items)
            _options.AddItem(LocExtensions.LocalizeOrRaw(text), value);

        UpdateButtonColors();

        Help.Visible = guides != null;
        _guides = guides;

        TitleLabel.Text = title;
        TitleLabel.MinSize = new Vector2(titleSize, 0f);
        TitleLabel.MaxSize = new Vector2(titleSize, 0f);
        TitleLabel.ClipText = true;
        TitleLabel.ToolTip = description;

        if (optionsContainerWidth is float width)
        {
            OptionsContainer.MinWidth = width;
            OptionsContainer.MaxSize = new Vector2(width, 0f);
        }
        else
        {
            OptionsContainer.MinWidth = 0;
            OptionsContainer.MaxSize = Vector2.Zero;
        }

        if (icon != null)
        {
            AddChild(icon);
            icon.SetPositionFirst();
        }

        OptionsContainer.AddChild(_options);
        OptionsContainer.AddChild(_lockStripe);
    }

    public void LockRequirements(FormattedMessage requirements)
    {
        _lockIcon.SetRequirements(requirements);
        _lockStripe.Visible = true;
        _options.Visible = false;
    }

    public void UnlockRequirements()
    {
        _lockStripe.Visible = false;
        _options.Visible = true;
    }

    private Button GenerateButton(string text, int value)
    {
        var button = new Button
        {
            Text = text,
            MinWidth = _optionButtonMinWidth,
            MinHeight = _optionButtonMinHeight,
            HorizontalExpand = true,
            ClipText = true,
        };

        if (_buttonColors != null && _buttonColors.TryGetValue(value, out var color))
            _coloredButtons.Add((button, color));

        return button;
    }

    private void UpdateButtonColors()
    {
        foreach (var (button, color) in _coloredButtons)
            ApplyButtonColor(button, color, button.Pressed);
    }

    private static void ApplyButtonColor(Button button, Color color, bool selected)
    {
        button.ModulateSelfOverride = null;
        button.Label.FontColorOverride = null;
        button.StyleBoxOverride = null;

        if (!selected)
            return;

        button.StyleBoxOverride = LobbyUiStyles.SelectedPriorityButton(color);
        button.ModulateSelfOverride = Color.White;
        button.Label.FontColorOverride = Color.White;
    }

    public void Select(int id)
    {
        _options.Select(id);
        UpdateButtonColors();
    }
}
